// Norwegian bokmål strings for Media Chrome's built-in accessible names (aria-label etc).
// Media Chrome only ships English by default; without this, screen-reader users
// hear English control names in an otherwise Norwegian-language app.
import { addTranslation, setLanguage } from 'media-chrome/utils/i18n.js'

const Nb = {
  'Start airplay': 'Start AirPlay',
  'Stop airplay': 'Stopp AirPlay',
  Audio: 'Lyd',
  Captions: 'Undertekster',
  'Enable captions': 'Vis undertekster',
  'Disable captions': 'Skjul undertekster',
  'Start casting': 'Start Cast',
  'Stop casting': 'Stopp Cast',
  'Enter fullscreen mode': 'Gå til fullskjerm',
  'Exit fullscreen mode': 'Avslutt fullskjerm',
  Mute: 'Demp lyd',
  Unmute: 'Slå på lyd',
  Loop: 'Gjenta',
  'Enter picture in picture mode': 'Bilde-i-bilde',
  'Exit picture in picture mode': 'Avslutt bilde-i-bilde',
  Play: 'Spill av',
  Pause: 'Pause',
  'Playback rate': 'Avspillingshastighet',
  'Playback rate {playbackRate}': 'Avspillingshastighet {playbackRate}',
  Quality: 'Kvalitet',
  'Seek backward': 'Spol tilbake',
  'Seek forward': 'Spol fremover',
  Settings: 'Innstillinger',
  Auto: 'Auto',
  'audio player': 'lydspiller',
  'video player': 'videospiller',
  volume: 'volum',
  seek: 'spol',
  'closed captions': 'undertekster',
  'current playback rate': 'gjeldende avspillingshastighet',
  'playback time': 'avspillingstid',
  'media loading': 'laster media',
  settings: 'innstillinger',
  'audio tracks': 'lydspor',
  quality: 'kvalitet',
  play: 'spill av',
  pause: 'pause',
  mute: 'demp lyd',
  unmute: 'slå på lyd',
  'chapter: {chapterName}': 'kapittel: {chapterName}',
  live: 'direkte',
  Off: 'Av',
  'start airplay': 'start airplay',
  'stop airplay': 'stopp airplay',
  'start casting': 'start cast',
  'stop casting': 'stopp cast',
  'enter fullscreen mode': 'gå til fullskjerm',
  'exit fullscreen mode': 'avslutt fullskjerm',
  'enter picture in picture mode': 'bilde-i-bilde',
  'exit picture in picture mode': 'avslutt bilde-i-bilde',
  'seek to live': 'spol til direkte',
  'playing live': 'spiller direkte',
  'seek back {seekOffset} seconds': 'spol tilbake {seekOffset} sekunder',
  'seek forward {seekOffset} seconds': 'spol fremover {seekOffset} sekunder',
  'Network Error': 'Nettverksfeil',
  'Decode Error': 'Dekodingsfeil',
  'Source Not Supported': 'Kilden støttes ikke',
  'Encryption Error': 'Krypteringsfeil',
  'A network error caused the media download to fail.': 'En nettverksfeil stanset nedlastingen av videoen.',
  'A media error caused playback to be aborted. The media could be corrupt or your browser does not support this format.':
    'En feil stanset avspillingen. Filen kan være skadet, eller nettleseren støtter ikke formatet.',
  'An unsupported error occurred. The server or network failed, or your browser does not support this format.':
    'En ukjent feil oppstod. Serveren eller nettverket sviktet, eller nettleseren støtter ikke formatet.',
  'The media is encrypted and there are no keys to decrypt it.':
    'Videoen er kryptert, og det finnes ingen nøkkel til å dekryptere den.',
  hour: 'time',
  hours: 'timer',
  minute: 'minutt',
  minutes: 'minutter',
  second: 'sekund',
  seconds: 'sekunder',
  '{time} remaining': '{time} igjen',
  '{currentTime} of {totalTime}': '{currentTime} av {totalTime}',
  'video not loaded, unknown time.': 'video ikke lastet, ukjent tid.',
}

addTranslation('nb', Nb)
setLanguage('nb')
